markdown: rdiscount
highlighter: rouge
pygments: true
baseurl: /fnews
title: FNews NNTP Server
mypages:
 - name: Home
   url: /
 - name: Blog
   url: /blog.html
 - name: Documentation
   url: /docs/

